name: whatsapp_clone
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
  cloud_firestore: ^4.17.3
  firebase_storage: ^11.7.5
  country_picker_plus: ^2.0.2
  country_picker: ^2.0.26
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.13.1"
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.10
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10

flutter_launcher_icons:
  image_path: "assets/icon_app.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/backgroundImage.png
    - assets/bg.png
    - assets/phone.png
    - assets/icon_app.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
